import "./main.css";
import ProviderWrapper from "./ProviderWrapper";
import { Open_Sans } from "next/font/google";
import Hero from "./components/Hero";
import Navbar from "./components/navbar/Navbar";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <ProviderWrapper>
          <Navbar />
          <Hero />
          {children}
        </ProviderWrapper>
      </body>
    </html>
  );
}
