import "./main.css";
import ProviderWrapper from "./ProviderWrapper";
import { Open_Sans } from "next/font/google";
import Hero from "./components/Hero";
import Navbar from "./components/navbar/Navbar";

import { dir } from "i18next";
import { languages } from "../i18n/settings";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Q8hand Clean",
  // description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export default function RootLayout({ children, params: { lng } }) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={openSans.className}>
        <ProviderWrapper lng={lng}>{children}</ProviderWrapper>
      </body>
    </html>
  );
}
